Implement IfEval casing, comma, and sentence count rules.
macrocosm-os/finetuning pull request #116
Opened 2024-11-14 00:58 UTC by Sid-Data-Universe

2024-11-14 06:04 UTC, RusticLuftig requested changes
This LGTM but will need a slight update to include the index in get_prompt and matches.

2024-11-14 06:04 UTC, RusticLuftig commented on tests/finetune/eval/if_eval/test_casing.py
> +        self.assertTrue(rule.matches("THIS  IS A\n TEST, ALL UPPERCASE!"))
Can we also verify numbers are ignored?

2024-11-16 16:52 UTC, Sid-Data-Universe commented on tests/finetune/eval/if_eval/test_casing.py
> +        self.assertTrue(rule.matches("THIS  IS A\n TEST, ALL UPPERCASE!"))
Added.

2024-11-16 18:48 UTC, RusticLuftig approved these changes

2024-11-16 18:53 UTC, merged